"use client";
import { type FormEvent, useEffect, useState } from "react";
import type { DistributionCampaign, LearningInsight, PerformanceRecord } from "@atlas/types";
import "../mission.css";
import "./learning.css";
const api = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:3333";

export default function LearningPage() {
  const [token, setToken] = useState(""), [campaigns, setCampaigns] = useState<DistributionCampaign[]>([]), [records, setRecords] = useState<PerformanceRecord[]>([]), [insights, setInsights] = useState<LearningInsight[]>([]), [campaignId, setCampaignId] = useState(""), [metrics, setMetrics] = useState({ impressions: "1000", clicks: "100", conversions: "10", cost: "50", revenue: "150" }), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const headers = (json = false) => ({ authorization: `Bearer ${token}`, ...(json ? { "content-type": "application/json" } : {}) });
  async function refresh(activeToken = token) { const auth = { authorization: `Bearer ${activeToken}` }; const responses = await Promise.all([fetch(`${api}/distribution/campaigns`, { headers: auth }), fetch(`${api}/learning/performance`, { headers: auth }), fetch(`${api}/learning/insights`, { headers: auth })]); if (responses.some((item) => !item.ok)) throw new Error("Sessão expirada ou API indisponível"); const [nextCampaigns, nextRecords, nextInsights] = await Promise.all(responses.map((item) => item.json())); const completed = (nextCampaigns as DistributionCampaign[]).filter((item) => item.status === "completed"); setCampaigns(completed); setRecords(nextRecords); setInsights(nextInsights); setCampaignId((value) => value || completed[0]?.id || ""); }
  useEffect(() => { const saved = localStorage.getItem("atlas_token") ?? ""; setToken(saved); if (saved) void refresh(saved).catch((reason) => setError(reason.message)); }, []);
  async function record(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const response = await fetch(`${api}/learning/performance`, { method: "POST", headers: headers(true), body: JSON.stringify({ campaignId, metrics: Object.fromEntries(Object.entries(metrics).map(([key, value]) => [key, Number(value)])), dataKind: "simulated", source: "manual:v0.8", observedAt: new Date().toISOString() }) }); if (!response.ok) throw new Error((await response.json()).message); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Falha ao registrar métricas"); } finally { setBusy(false); } }
  async function analyze(opportunityId: string) { setBusy(true); setError(""); try { const response = await fetch(`${api}/learning/opportunities/${opportunityId}/analyze`, { method: "POST", headers: headers() }); if (!response.ok) throw new Error((await response.json()).message); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Falha ao analisar"); } finally { setBusy(false); } }
  if (!token) return <main className="learning-page"><section className="panel"><h1>Entre primeiro no Atlas</h1><a href="/">Voltar ao login</a></section></main>;
  const selected = campaigns.find((item) => item.id === campaignId);
  return <main className="mission-shell"><aside className="sidebar"><a className="brand" href="/"><span className="brand-mark">A</span>atlas<span className="muted">.os</span></a><nav><a className="nav-link" href="/">Oportunidades</a><a className="nav-link" href="/content">Conteúdo</a><a className="nav-link" href="/distribution">Distribuição</a><a className="nav-link active">Aprendizado</a></nav></aside><section className="content mission-content"><header className="topbar"><div><span className="eyebrow">LEARNING ENGINE · v0.8</span><h1>Resultados que viram<br/><em>decisões melhores.</em></h1></div></header>{error && <p className="error-banner">{error}</p>}<section className="learning-grid"><form className="panel mission-form" onSubmit={record}><span className="eyebrow">MÉTRICAS</span><h2>Registrar desempenho</h2><label>Campanha concluída<select value={campaignId} onChange={(event) => setCampaignId(event.target.value)} required><option value="">Selecione</option>{campaigns.map((item) => <option key={item.id} value={item.id}>{item.utm.campaign} · {item.mode}</option>)}</select></label>{Object.entries(metrics).map(([key, value]) => <label key={key}>{key}<input type="number" min="0" step="any" value={value} onChange={(event) => setMetrics((current) => ({ ...current, [key]: event.target.value }))}/></label>)}<small>Entrada marcada como simulada. Dados reais exigem fonte confirmada.</small><button className="new-button" disabled={busy || !campaignId}>Calcular desempenho</button>{selected && <button type="button" className="analyze-button" disabled={busy} onClick={() => void analyze(selected.opportunityId)}>Gerar recomendação</button>}</form><section className="panel"><span className="eyebrow">DESEMPENHO</span><h2>Experimentos</h2>{records.map((record) => <article className="metric-card" key={record.id}><strong>ROI {record.roi ?? "—"}%</strong><span>CTR {record.ctr}%</span><span>Conversão {record.conversionRate}%</span><span>Lucro {record.profit}</span><small>{record.dataKind} · {record.source}</small></article>)}{!records.length && <p className="empty-state">Nenhuma métrica registrada.</p>}</section></section><section className="insight-list"><h2>Recomendações</h2>{insights.map((insight) => <article className="panel" key={insight.id}><span className="mission-status">{insight.dataKind}</span><h3>{insight.summary}</h3><p>{insight.recommendation}</p><strong>Confiança {Math.round(insight.confidence * 100)}%</strong></article>)}</section></section></main>;
}
