"use client";
import { FormEvent, useEffect, useState } from "react";
import type { AtlasStatus, AuthSession, Decision, Mission } from "@atlas/types";
const api = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:3333";

export default function Home() {
  const [token, setToken] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [name, setName] = useState(""); const [registering, setRegistering] = useState(false);
  const [status,setStatus]=useState<AtlasStatus|null>(null),[missions,setMissions]=useState<Mission[]>([]),[decisions,setDecisions]=useState<Record<string,Decision>>({});
  const [title,setTitle]=useState("Analisar oportunidade de mercado"),[objective,setObjective]=useState("Avaliar demanda para um novo serviço B2B"),[context,setContext]=useState(""),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState("");
  const headers = (json = false) => ({ authorization: `Bearer ${token}`, ...(json ? { "content-type": "application/json" } : {}) });
  useEffect(() => { const saved = localStorage.getItem("atlas_token") ?? ""; setToken(saved); }, []);
  useEffect(() => { if (token) void refresh(); }, [token]);
  async function authenticate(e: FormEvent) { e.preventDefault(); setError(""); const endpoint = registering ? "register" : "login"; const response = await fetch(`${api}/auth/${endpoint}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email, password, name }) }); if (!response.ok) { setError((await response.json()).message ?? "Falha na autenticação"); return; } const session = await response.json() as AuthSession; localStorage.setItem("atlas_token", session.token); setToken(session.token); }
  async function refresh(){try{const[s,m]=await Promise.all([fetch(`${api}/atlas/status`),fetch(`${api}/missions`,{headers:headers()})]);if(!s.ok||!m.ok)throw new Error();const list=await m.json() as Mission[];setStatus(await s.json());setMissions(list);setError("");const loaded=await Promise.all(list.filter(x=>x.decisionId).map(async x=>[x.id,await(await fetch(`${api}/decisions/${x.decisionId}`,{headers:headers()})).json()] as const));setDecisions(Object.fromEntries(loaded))}catch{setError("A API do Atlas não está acessível ou a sessão expirou.")}}
  async function createMission(e:FormEvent){e.preventDefault();setBusy("create");setError("");try{const r=await fetch(`${api}/missions`,{method:"POST",headers:headers(true),body:JSON.stringify({title,objective,context})});if(!r.ok)throw new Error("Não foi possível criar a missão");const mission=await r.json() as Mission;setMissions(c=>[mission,...c]);setTitle("");setObjective("");setContext("")}catch(e){setError(e instanceof Error?e.message:"Erro inesperado")}finally{setBusy(null)}}
  async function execute(m:Mission){setBusy(m.id);setError("");try{const r=await fetch(`${api}/missions/${m.id}/execute`,{method:"POST",headers:headers(true),body:"{}"});if(!r.ok)throw new Error("A análise falhou");const d=await r.json() as Decision;setDecisions(c=>({...c,[m.id]:d}));setMissions(c=>c.map(x=>x.id===m.id?{...x,status:"completed",decisionId:d.id}:x))}catch(e){setError(e instanceof Error?e.message:"Erro inesperado")}finally{setBusy(null)}}
  function logout(){localStorage.removeItem("atlas_token");setToken("");setMissions([])}

  if (!token) return <main className="mission-shell"><section className="content mission-content"><form className="panel mission-form" onSubmit={authenticate}><span className="eyebrow">ATLAS MULTIUSER</span><h1>{registering ? "Criar conta" : "Entrar"}</h1>{registering&&<label>Nome<input value={name} onChange={e=>setName(e.target.value)} required/></label>}<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Senha<input type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<p className="error-banner">{error}</p>}<button className="new-button">{registering?"Criar conta":"Entrar"}</button><button type="button" className="text-button" onClick={()=>setRegistering(!registering)}>{registering?"Já tenho conta":"Criar primeira conta"}</button></form></section></main>;
  return <main className="mission-shell"><aside className="sidebar"><a className="brand"><span className="brand-mark">A</span>atlas<span className="muted">.os</span></a><nav><a className="nav-link active">Mission Control</a><a className="nav-link" href="/operation">Operação</a></nav><button className="text-button" onClick={logout}>Sair</button><div className="core-state"><span className={`state-dot ${status?.lifecycle==="running"?"online":""}`}/><div><strong>{status?.lifecycle==="running"?"Atlas operacional":"Conectando"}</strong><small>{status?`${status.ai.provider} · ${status.ai.model}`:"Verificando núcleo"}</small></div></div></aside><section className="content mission-content"><header className="topbar"><div><span className="eyebrow">MISSION CONTROL</span><h1>Decisões com contexto,<br/><em>isoladas por usuário.</em></h1></div></header>{error&&<p className="error-banner">{error}</p>}<section className="mission-grid"><form className="panel mission-form" onSubmit={createMission}><span className="eyebrow">NOVA MISSÃO</span><h2>O que o Atlas deve analisar?</h2><label>Título<input value={title} onChange={e=>setTitle(e.target.value)} required/></label><label>Objetivo<textarea value={objective} onChange={e=>setObjective(e.target.value)} minLength={10} required/></label><label>Contexto<textarea value={context} onChange={e=>setContext(e.target.value)}/></label><button className="new-button" disabled={busy==="create"}>Criar missão</button></form><section className="panel system-panel"><span className="eyebrow">ATLAS CORE</span><h2>{status?.version}</h2>{status?.modules.map(x=><div className="module-row" key={x.name}><span className="state-dot online"/>{x.name}<small>{x.status}</small></div>)}</section></section><section className="history"><div className="panel-title"><h2>Missões e decisões</h2><button className="text-button" onClick={()=>void refresh()}>Atualizar</button></div><div className="mission-list">{missions.map(m=>{const d=decisions[m.id];return <article className="panel mission-card" key={m.id}><div className="mission-heading"><div><span className={`mission-status ${m.status}`}>{m.status}</span><h3>{m.title}</h3><p>{m.objective}</p></div>{m.status!=="completed"&&<button className="new-button" disabled={busy===m.id} onClick={()=>void execute(m)}>Executar análise</button>}</div>{d&&<div className="decision"><h4>{d.recommendation}</h4><p>{d.rationale}</p><strong>Confiança {Math.round((d.adjustedConfidence??d.confidence)*100)}%</strong><h5>Plano</h5><ol>{(d.executionPlan??d.nextSteps).map(step=><li key={step}>{step}</li>)}</ol><small>{d.provider} · {d.model}</small></div>}</article>})}</div></section></section></main>;
}
