"use client";
import { type FormEvent, useEffect, useState } from "react";
import type { LearningInsight, ScalePolicy, ScaleProposal } from "@atlas/types";
import "../mission.css";
import "./scale.css";
const api = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:3333";

export default function ScalePage() {
  const [token, setToken] = useState(""), [insights, setInsights] = useState<LearningInsight[]>([]), [policies, setPolicies] = useState<ScalePolicy[]>([]), [proposals, setProposals] = useState<ScaleProposal[]>([]), [policyId, setPolicyId] = useState(""), [insightId, setInsightId] = useState(""), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const headers = (json = false) => ({ authorization: `Bearer ${token}`, ...(json ? { "content-type": "application/json" } : {}) });
  async function refresh(activeToken = token) { const auth = { authorization: `Bearer ${activeToken}` }; const responses = await Promise.all([fetch(`${api}/learning/insights`, { headers: auth }), fetch(`${api}/scale/policies`, { headers: auth }), fetch(`${api}/scale/proposals`, { headers: auth })]); if (responses.some((item) => !item.ok)) throw new Error("Sessão expirada ou API indisponível"); const [nextInsights, nextPolicies, nextProposals] = await Promise.all(responses.map((item) => item.json())); setInsights(nextInsights); setPolicies(nextPolicies); setProposals(nextProposals); setInsightId((value) => value || nextInsights[0]?.id || ""); setPolicyId((value) => value || nextPolicies[0]?.id || ""); }
  useEffect(() => { const saved = localStorage.getItem("atlas_token") ?? ""; setToken(saved); if (saved) void refresh(saved).catch((reason) => setError(reason.message)); }, []);
  async function createPolicy() { setBusy(true); setError(""); try { const response = await fetch(`${api}/scale/policies`, { method: "POST", headers: headers(true), body: JSON.stringify({ name: "Política segura — orçamento zero", maxTotalBudget: 0, maxDailyBudget: 0, maxIncreasePercent: 20, minRoiPercent: 50, minConversions: 5, maxCac: 20, requireConfirmedData: true }) }); if (!response.ok) throw new Error((await response.json()).message); const policy = await response.json() as ScalePolicy; setPolicyId(policy.id); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Falha ao criar política"); } finally { setBusy(false); } }
  async function propose(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const response = await fetch(`${api}/scale/proposals`, { method: "POST", headers: headers(true), body: JSON.stringify({ policyId, insightId, currentBudget: 0 }) }); if (!response.ok) throw new Error((await response.json()).message); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Falha ao simular escala"); } finally { setBusy(false); } }
  async function advance(proposal: ScaleProposal, action: "review" | "simulate") { setBusy(true); try { const response = await fetch(`${api}/scale/proposals/${proposal.id}/${action}`, { method: "POST", headers: headers(action === "review"), ...(action === "review" ? { body: JSON.stringify({ status: "approved" }) } : {}) }); if (!response.ok) throw new Error((await response.json()).message); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Falha ao avançar proposta"); } finally { setBusy(false); } }
  if (!token) return <main className="scale-page"><section className="panel"><h1>Entre primeiro no Radar de Escolhas</h1><a href="/">Voltar ao login</a></section></main>;
  return <main className="mission-shell"><aside className="sidebar"><a className="brand" href="/"><span className="brand-mark">R</span>Radar<span className="muted"> de Escolhas</span></a><nav><a className="nav-link" href="/">Oportunidades</a><a className="nav-link" href="/learning">Aprendizado</a><a className="nav-link active">Escala</a></nav></aside><section className="content mission-content"><header className="topbar"><div><span className="eyebrow">SCALE ENGINE · v0.9</span><h1>Escalar somente<br/><em>com limites claros.</em></h1></div></header>{error && <p className="error-banner">{error}</p>}<section className="scale-grid"><form className="panel mission-form" onSubmit={propose}><span className="eyebrow">POLÍTICA FINANCEIRA</span><h2>Simulação segura</h2>{!policies.length && <button type="button" className="new-button" onClick={() => void createPolicy()} disabled={busy}>Criar política de orçamento zero</button>}<label>Política<select value={policyId} onChange={(event) => setPolicyId(event.target.value)} required><option value="">Selecione</option>{policies.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Insight<select value={insightId} onChange={(event) => setInsightId(event.target.value)} required><option value="">Selecione</option>{insights.map((item) => <option key={item.id} value={item.id}>{item.summary}</option>)}</select></label><small>Execução real desativada. Orçamento atual e proposto: zero.</small><button className="new-button" disabled={busy || !policyId || !insightId}>Gerar proposta</button></form><section className="panel"><span className="eyebrow">PORTFÓLIO</span><h2>Propostas de escala</h2>{proposals.map((proposal) => <article className="scale-card" key={proposal.id}><span className="mission-status">{proposal.status}</span><h3>{proposal.action}</h3><p>{proposal.rationale}</p><strong>{proposal.currentBudget} → {proposal.proposedBudget}</strong><small>{proposal.dataKind} · riscos: {proposal.riskFlags.join(", ") || "nenhum"}</small>{proposal.status === "draft" && <button className="new-button" disabled={busy} onClick={() => void advance(proposal, "review")}>Aprovar simulação</button>}{proposal.status === "approved" && <button className="new-button" disabled={busy} onClick={() => void advance(proposal, "simulate")}>Executar simulação</button>}</article>)}{!proposals.length && <p className="empty-state">Nenhuma proposta criada.</p>}</section></section></section></main>;
}
