import type { CompanyCycle, CompanyStage, ContentAsset, DistributionCampaign, LearningInsight, MarketOpportunity, PerformanceRecord, ScaleProposal } from "@atlas/types";
import type { CollectionStore, Guardian } from "./index.js";
import { AgentRuntime, PermissionManager } from "./v03.js";

export type CompanyStores = { cycles: CollectionStore<CompanyCycle>; opportunities: CollectionStore<MarketOpportunity>; assets: CollectionStore<ContentAsset>; campaigns: CollectionStore<DistributionCampaign>; performance: CollectionStore<PerformanceRecord>; insights: CollectionStore<LearningInsight>; proposals: CollectionStore<ScaleProposal> };
export class CompanyOrchestrator {
  constructor(private readonly stores: CompanyStores, private readonly guardian: Guardian, private readonly runtime: AgentRuntime, private readonly permissions: PermissionManager) { permissions.grant("agent:atlas-coo", ["company.assess"]); if (!runtime.listAgents().some((agent) => agent.id === "atlas-coo")) runtime.register({ id: "atlas-coo", name: "Atlas COO Agent", role: "Coordena o ciclo comercial e opera por exceção", status: "registered", permissions: permissions.list("agent:atlas-coo") }); runtime.start("atlas-coo"); }
  async assess(ownerId: string): Promise<CompanyCycle> { this.permissions.require("agent:atlas-coo", "company.assess"); const cycle = await this.runtime.run("atlas-coo", crypto.randomUUID(), async () => { const [opportunities, assets, campaigns, performance, insights, proposals] = await Promise.all([this.owned(this.stores.opportunities, ownerId), this.owned(this.stores.assets, ownerId), this.owned(this.stores.campaigns, ownerId), this.owned(this.stores.performance, ownerId), this.owned(this.stores.insights, ownerId), this.owned(this.stores.proposals, ownerId)]); const qualified = opportunities.filter((item) => item.status === "qualified"); const approvedAssets = assets.filter((item) => item.status === "approved"); const completedCampaigns = campaigns.filter((item) => item.status === "completed"); const confirmedPerformance = performance.filter((item) => item.dataKind === "confirmed"); const confirmedInsights = insights.filter((item) => item.dataKind === "confirmed"); const simulatedScales = proposals.filter((item) => item.status === "simulated"); const stages: CompanyStage[] = [stage("research", qualified.length, "Oportunidades qualificadas"), stage("content", approvedAssets.length, "Conteúdos aprovados"), stage("distribution", completedCampaigns.length, "Campanhas concluídas"), stage("measurement", confirmedPerformance.length, "Resultados confirmados"), stage("learning", confirmedInsights.length, "Insights confirmados"), stage("scaling", simulatedScales.length, "Propostas de escala simuladas")]; const blockers = stages.filter((item) => item.status === "blocked").map((item) => `${item.name}: ${item.detail}`); const nextAction = next(stages); return { result: { id: crypto.randomUUID(), ownerId, mode: "safe", status: blockers.length ? "blocked" : "ready", stages, nextAction, blockers, externalPublishingEnabled: false, financialExecutionEnabled: false, createdAt: new Date().toISOString() } satisfies CompanyCycle, memoryUsed: stages.reduce((sum, item) => sum + item.count, 0), provider: "atlas-company-rules" }; }, 30_000, ownerId); await this.stores.cycles.save([cycle, ...await this.stores.cycles.load()]); await this.guardian.record("company-orchestrator", "company.assess", { ownerId, cycleId: cycle.id, status: cycle.status, blockers: cycle.blockers.join(" | "), nextAction: cycle.nextAction, externalPublishingEnabled: false, financialExecutionEnabled: false }, "success"); return cycle; }
  async list(ownerId: string) { return this.owned(this.stores.cycles, ownerId); }
  close() { this.stores.cycles.close?.(); }
  private async owned<T extends { ownerId: string }>(store: CollectionStore<T>, ownerId: string) { return (await store.load()).filter((item) => item.ownerId === ownerId); }
}
function stage(name: CompanyStage["name"], count: number, label: string): CompanyStage { return { name, status: count ? "completed" : "blocked", count, detail: count ? `${count} ${label.toLowerCase()}` : `${label} ausentes` }; }
function next(stages: CompanyStage[]) { const blocked = stages.find((item) => item.status === "blocked"); const actions: Record<CompanyStage["name"], string> = { research: "Pesquisar e qualificar uma oportunidade comercial.", content: "Criar e aprovar conteúdo para a melhor oportunidade.", distribution: "Preparar e executar uma distribuição controlada.", measurement: "Conectar uma fonte real e registrar métricas confirmadas.", learning: "Gerar aprendizado usando resultados confirmados.", scaling: "Simular uma proposta de escala sob política financeira." }; return blocked ? actions[blocked.name] : "Ciclo preparado; manter supervisão humana e monitorar exceções."; }
