import type { ContentAsset, CreateDistributionInput, DistributionCampaign } from "@atlas/types";
import type { CollectionStore, Guardian } from "./index.js";
import { AgentRuntime, PermissionManager } from "./v03.js";

export class DistributionCenter {
  constructor(private readonly campaigns: CollectionStore<DistributionCampaign>, private readonly assets: CollectionStore<ContentAsset>, private readonly guardian: Guardian, private readonly runtime: AgentRuntime, private readonly permissions: PermissionManager) {
    for (const [id, name, role] of [["social-distribution", "Social Distribution Agent", "Prepara e agenda distribuição multicanal"], ["traffic-tracking", "Traffic Tracking Agent", "Cria links rastreáveis e registra entregas"]] as const) {
      permissions.grant(`agent:${id}`, ["distribution.prepare", "distribution.execute"]); if (!runtime.listAgents().some((agent) => agent.id === id)) runtime.register({ id, name, role, status: "registered", permissions: permissions.list(`agent:${id}`) }); runtime.start(id);
    }
  }
  async create(ownerId: string, input: CreateDistributionInput): Promise<DistributionCampaign> {
    this.permissions.require("agent:social-distribution", "distribution.prepare"); const asset = await this.findAsset(input.assetId, ownerId); if (!asset) throw new Error("Content asset not found"); if (asset.status !== "approved") throw new Error("Only approved content can be distributed"); if (asset.channel !== input.channel) throw new Error("Distribution channel must match the approved asset");
    const mode = input.mode ?? "dry_run"; if (mode === "live") throw new Error("Live distribution requires an installed channel connector and explicit authorization");
    const utm = { source: input.channel, medium: medium(input.channel), campaign: slug(input.campaignName), content: asset.id.slice(0, 8) }; const trackingUrl = withTracking(input.targetUrl, utm); const now = new Date().toISOString();
    const campaign: DistributionCampaign = { id: crypto.randomUUID(), ownerId, assetId: asset.id, opportunityId: asset.opportunityId, channel: input.channel, destination: input.destination.trim(), scheduledAt: new Date(input.scheduledAt).toISOString(), status: "draft", mode, trackingUrl, utm, createdAt: now, updatedAt: now };
    await this.campaigns.save([campaign, ...await this.campaigns.load()]); await this.guardian.record("distribution-center", "distribution.create", { ownerId, campaignId: campaign.id, assetId: asset.id, channel: campaign.channel, mode }, "success"); return campaign;
  }
  async approve(ownerId: string, id: string): Promise<DistributionCampaign | undefined> { const items = await this.campaigns.load(); const item = items.find((entry) => entry.id === id && entry.ownerId === ownerId); if (!item) return undefined; if (item.status !== "draft") throw new Error("Only draft campaigns can be approved"); item.status = "approved"; item.approvedAt = new Date().toISOString(); item.updatedAt = item.approvedAt; await this.campaigns.save(items); await this.guardian.record("distribution-center", "distribution.approve", { ownerId, campaignId: id, channel: item.channel, mode: item.mode }, "success"); return item; }
  async schedule(ownerId: string, id: string): Promise<DistributionCampaign | undefined> { const items = await this.campaigns.load(); const item = items.find((entry) => entry.id === id && entry.ownerId === ownerId); if (!item) return undefined; if (item.status !== "approved") throw new Error("Campaign must be approved before scheduling"); item.status = "scheduled"; item.updatedAt = new Date().toISOString(); await this.campaigns.save(items); await this.guardian.record("distribution-center", "distribution.schedule", { ownerId, campaignId: id, scheduledAt: item.scheduledAt, mode: item.mode }, "success"); return item; }
  async execute(ownerId: string, id: string): Promise<DistributionCampaign | undefined> { this.permissions.require("agent:traffic-tracking", "distribution.execute"); const items = await this.campaigns.load(); const item = items.find((entry) => entry.id === id && entry.ownerId === ownerId); if (!item) return undefined; if (item.status !== "scheduled") throw new Error("Campaign must be scheduled before execution"); if (item.mode !== "dry_run") throw new Error("No live connector is configured"); const result = await this.runtime.run("social-distribution", item.id, async () => ({ result: { delivered: false, detail: `Dry run validated for ${item.channel}; no external publication occurred.` }, memoryUsed: 0, provider: "local-distribution-simulator" }), 30_000, ownerId); item.status = "completed"; item.executedAt = new Date().toISOString(); item.updatedAt = item.executedAt; item.result = result; await this.campaigns.save(items); await this.guardian.record("distribution-center", "distribution.execute", { ownerId, campaignId: id, channel: item.channel, mode: item.mode, delivered: result.delivered, trackingUrl: item.trackingUrl }, "success"); return item; }
  async list(ownerId: string) { return (await this.campaigns.load()).filter((item) => item.ownerId === ownerId); }
  async get(id: string, ownerId: string) { return (await this.campaigns.load()).find((item) => item.id === id && item.ownerId === ownerId); }
  close() { this.campaigns.close?.(); }
  private async findAsset(id: string, ownerId: string) { return (await this.assets.load()).find((item) => item.id === id && item.ownerId === ownerId); }
}
function slug(value: string) { return value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 80) || "atlas-campaign"; }
function medium(channel: string) { return channel === "email" ? "email" : channel === "blog" || channel === "landing-page" ? "owned" : "social"; }
function withTracking(target: string, utm: DistributionCampaign["utm"]) { const url = new URL(target); for (const [key, value] of Object.entries(utm)) url.searchParams.set(`utm_${key}`, value); return url.toString(); }
