import type { CreateScalePolicyInput, CreateScaleProposalInput, LearningInsight, PerformanceRecord, ScalePolicy, ScaleProposal } from "@atlas/types";
import type { CollectionStore, Guardian } from "./index.js";
import { AgentRuntime, PermissionManager } from "./v03.js";

export class ScaleEngine {
  constructor(private readonly policies: CollectionStore<ScalePolicy>, private readonly proposals: CollectionStore<ScaleProposal>, private readonly insights: CollectionStore<LearningInsight>, private readonly records: CollectionStore<PerformanceRecord>, private readonly guardian: Guardian, private readonly runtime: AgentRuntime, private readonly permissions: PermissionManager) {
    for (const [id, name, role] of [["finance", "Finance Agent", "Aplica limites de orçamento, margem e risco"], ["scale", "Scale Agent", "Propõe escala controlada de iniciativas vencedoras"]] as const) { permissions.grant(`agent:${id}`, ["scale.policy", "scale.propose", "scale.simulate"]); if (!runtime.listAgents().some((agent) => agent.id === id)) runtime.register({ id, name, role, status: "registered", permissions: permissions.list(`agent:${id}`) }); runtime.start(id); }
  }
  async createPolicy(ownerId: string, input: CreateScalePolicyInput): Promise<ScalePolicy> { this.permissions.require("agent:finance", "scale.policy"); validatePolicy(input); const now = new Date().toISOString(); const policy: ScalePolicy = { id: crypto.randomUUID(), ownerId, ...input, name: input.name.trim(), requireConfirmedData: input.requireConfirmedData ?? true, requireHumanApproval: true, liveExecutionEnabled: false, createdAt: now, updatedAt: now }; await this.policies.save([policy, ...await this.policies.load()]); await this.guardian.record("scale-engine", "scale.policy.create", { ownerId, policyId: policy.id, maxTotalBudget: policy.maxTotalBudget, maxDailyBudget: policy.maxDailyBudget, liveExecutionEnabled: false }, "success"); return policy; }
  async propose(ownerId: string, input: CreateScaleProposalInput): Promise<ScaleProposal> { this.permissions.require("agent:scale", "scale.propose"); const policy = (await this.policies.load()).find((item) => item.id === input.policyId && item.ownerId === ownerId); const insight = (await this.insights.load()).find((item) => item.id === input.insightId && item.ownerId === ownerId); if (!policy) throw new Error("Scale policy not found"); if (!insight) throw new Error("Learning insight not found"); const records = (await this.records.load()).filter((item) => insight.recordIds.includes(item.id) && item.ownerId === ownerId); const winner = records.find((item) => item.id === insight.winnerRecordId) ?? records[0]; if (!winner) throw new Error("Performance evidence not found"); const result = await this.runtime.run("scale", insight.id, async () => ({ result: decide(policy, insight, winner, input.currentBudget), memoryUsed: records.length, provider: "local-scale-rules" }), 30_000, ownerId); const now = new Date().toISOString(); const proposal: ScaleProposal = { id: crypto.randomUUID(), ownerId, policyId: policy.id, insightId: insight.id, opportunityId: insight.opportunityId, ...result, dataKind: insight.dataKind, status: "draft", createdAt: now, updatedAt: now }; await this.proposals.save([proposal, ...await this.proposals.load()]); await this.guardian.record("scale-engine", "scale.proposal.create", { ownerId, proposalId: proposal.id, action: proposal.action, currentBudget: proposal.currentBudget, proposedBudget: proposal.proposedBudget, dataKind: proposal.dataKind, risks: proposal.riskFlags.join(",") }, "success"); return proposal; }
  async review(ownerId: string, id: string, status: "approved" | "rejected") { const items = await this.proposals.load(); const item = items.find((entry) => entry.id === id && entry.ownerId === ownerId); if (!item) return undefined; if (item.status !== "draft") throw new Error("Only draft proposals can be reviewed"); item.status = status; item.updatedAt = new Date().toISOString(); if (status === "approved") item.approvedAt = item.updatedAt; await this.proposals.save(items); await this.guardian.record("scale-engine", "scale.proposal.review", { ownerId, proposalId: id, status, action: item.action, proposedBudget: item.proposedBudget }, "success"); return item; }
  async simulate(ownerId: string, id: string) { this.permissions.require("agent:scale", "scale.simulate"); const items = await this.proposals.load(); const item = items.find((entry) => entry.id === id && entry.ownerId === ownerId); if (!item) return undefined; if (item.status !== "approved") throw new Error("Proposal must be approved before simulation"); item.status = "simulated"; item.simulatedAt = new Date().toISOString(); item.updatedAt = item.simulatedAt; await this.proposals.save(items); await this.guardian.record("scale-engine", "scale.proposal.simulate", { ownerId, proposalId: id, action: item.action, proposedBudget: item.proposedBudget, financialTransaction: false }, "success"); return item; }
  async listPolicies(ownerId: string) { return (await this.policies.load()).filter((item) => item.ownerId === ownerId); }
  async listProposals(ownerId: string) { return (await this.proposals.load()).filter((item) => item.ownerId === ownerId); }
  close() { this.policies.close?.(); this.proposals.close?.(); }
}
function decide(policy: ScalePolicy, insight: LearningInsight, winner: PerformanceRecord, currentBudget: number): Pick<ScaleProposal, "action" | "rationale" | "currentBudget" | "proposedBudget" | "riskFlags"> { const risks: string[] = []; if (insight.dataKind !== "confirmed") risks.push("unconfirmed-data"); if (winner.metrics.conversions < policy.minConversions) risks.push("insufficient-conversions"); if ((winner.roi ?? -Infinity) < policy.minRoiPercent) risks.push("roi-below-threshold"); if (winner.cac === null || winner.cac > policy.maxCac) risks.push("cac-above-threshold"); if (policy.maxTotalBudget <= 0 || policy.maxDailyBudget <= 0) risks.push("zero-budget-policy"); const canScale = !risks.length; const increased = currentBudget * (1 + policy.maxIncreasePercent / 100); const proposedBudget = canScale ? round(Math.min(increased, policy.maxDailyBudget, policy.maxTotalBudget)) : currentBudget; return { action: canScale ? "scale" : winner.profit < 0 && insight.dataKind === "confirmed" ? "stop" : "hold", rationale: canScale ? `Escala simulada limitada a ${policy.maxIncreasePercent}% e aos tetos da política.` : `Escala bloqueada: ${risks.join(", ")}.`, currentBudget, proposedBudget, riskFlags: risks }; }
function validatePolicy(input: CreateScalePolicyInput) { for (const [key, value] of Object.entries(input)) if (key !== "name" && key !== "requireConfirmedData" && (!Number.isFinite(value) || Number(value) < 0)) throw new Error(`${key} must be non-negative`); if (!input.name.trim()) throw new Error("Policy name is required"); if (input.maxIncreasePercent > 100) throw new Error("Maximum increase cannot exceed 100%"); }
function round(value: number) { return Math.round(value * 100) / 100; }
