"use client";
import { useEffect, useState } from "react";
import type { AffiliateOffer, AutonomyJob, AutonomyPolicy, AutonomyStatus, DistributionCampaign, MarketOpportunity } from "@atlas/types";
const api = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:3333";

export default function OffersPage() {
  const [token, setToken] = useState(""); const [offers, setOffers] = useState<AffiliateOffer[]>([]); const [opportunities, setOpportunities] = useState<MarketOpportunity[]>([]); const [campaigns, setCampaigns] = useState<DistributionCampaign[]>([]); const [jobs, setJobs] = useState<AutonomyJob[]>([]); const [status, setStatus] = useState<AutonomyStatus | null>(null); const [policy, setPolicy] = useState<AutonomyPolicy | null>(null); const [error, setError] = useState("");
  useEffect(() => { const saved = localStorage.getItem("atlas_token") ?? ""; setToken(saved); if (saved) void refresh(saved); }, []);
  const auth = (active = token) => ({ authorization: `Bearer ${active}` });
  async function refresh(active = token) { try { const paths = ["market/offers", "market/opportunities", "distribution/campaigns", "autonomy/jobs", "autonomy/status", "autonomy/policy"]; const responses = await Promise.all(paths.map((path) => fetch(`${api}/${path}`, { headers: auth(active) }))); if (responses.some((item) => !item.ok)) throw new Error("Não foi possível carregar a operação"); const [o,p,c,j,s,a] = await Promise.all(responses.map((item) => item.json())); setOffers(o); setOpportunities(p); setCampaigns(c); setJobs(j); setStatus(s); setPolicy(a); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Falha ao carregar a Central de Ofertas"); } }
  async function toggle() { if (!policy) return; const response = await fetch(`${api}/autonomy/policy`, { method: "PATCH", headers: { ...auth(), "content-type": "application/json" }, body: JSON.stringify({ enabled: !policy.enabled }) }); if (!response.ok) { setError((await response.json()).message); return; } setPolicy(await response.json()); }
  const qualified = opportunities.filter((item) => item.status === "qualified").length; const delivered = campaigns.filter((item) => item.result?.delivered).length;
  return <main className="mission-shell"><aside className="sidebar"><a className="brand" href="/"><span className="brand-mark">A</span>Atlas<span className="muted"> 2.0</span></a><nav><a className="nav-link" href="/">Oportunidades</a><a className="nav-link active">Central de Ofertas</a><a className="nav-link" href="/distribution">Distribuição</a><a className="nav-link" href="/operation">Operação</a></nav></aside><section className="content offers-content"><header className="topbar"><div><span className="eyebrow">RADAR DE ESCOLHAS · OPERAÇÃO MULTICANAL</span><h1>Central de Ofertas</h1></div><button className="new-button" onClick={() => void refresh()}>Atualizar</button></header>{error && <p className="error-banner">{error}</p>}
  <section className="offers-hero"><div><span className={`autonomy-light ${policy?.enabled && status?.enabled ? "on" : ""}`}/><strong>{policy?.enabled && status?.enabled ? "Operação autônoma ativa" : "Ativação protegida"}</strong><p>O Atlas só entra em operação integral após o worker e os conectores oficiais passarem pela validação de produção.</p></div><button className="safety-button" onClick={() => void toggle()}>{policy?.enabled ? "Pausar empresa" : "Autorizar pela política"}</button></section>
  <section className="offer-metrics"><Metric value={offers.length} label="ofertas encontradas"/><Metric value={qualified} label="oportunidades qualificadas"/><Metric value={jobs.filter((item) => item.status === "pending" || item.status === "retry").length} label="tarefas aguardando"/><Metric value={delivered} label="publicações confirmadas"/></section>
  <section className="offers-grid"><article className="panel"><span className="eyebrow">FILA AUTÔNOMA</span><h2>Próximas ações</h2>{jobs.slice(0,8).map((job) => <div className="offer-row" key={job.id}><div><strong>{labelJob(job.kind)}</strong><small>{job.idempotencyKey}</small></div><span className={`job-status ${job.status}`}>{job.status}</span></div>)}{!jobs.length && <p className="empty-state">Nenhuma tarefa na fila.</p>}</article><article className="panel"><span className="eyebrow">CURADORIA</span><h2>Produtos em análise</h2>{offers.slice(0,8).map((offer) => <div className="offer-row" key={offer.id}><div><strong>{offer.name}</strong><small>{offer.provider} · {offer.notes || "aguardando validação"}</small></div>{offer.commission !== undefined && <b>{offer.commission}%</b>}</div>)}{!offers.length && <p className="empty-state">A descoberta automática ainda não foi ativada.</p>}</article></section>
  <section className="panel policy-panel"><span className="eyebrow">GUARDIÃO OPERACIONAL</span><h2>Limites atuais</h2><div className="policy-grid"><span><b>{policy?.maxPostsPerChannelPerDay ?? "—"}</b> publicações por canal/dia</span><span><b>{policy?.duplicateCooldownHours ?? "—"}h</b> sem repetir oferta</span><span><b>{policy?.quietHoursStart ?? "—"}–{policy?.quietHoursEnd ?? "—"}</b> horário silencioso</span><span><b>{policy?.requireLicensedMedia ? "Obrigatória" : "Desativada"}</b> licença de mídia</span></div></section>
  </section></main>;
}
function Metric({ value, label }: { value: number; label: string }) { return <article><strong>{value}</strong><span>{label}</span></article>; }
function labelJob(kind: AutonomyJob["kind"]) { return ({ discover_offers: "Descobrir ofertas", validate_offer: "Validar produto", prepare_content: "Preparar conteúdo", publish_content: "Publicar conteúdo", refresh_metrics: "Atualizar resultados", expire_offer: "Encerrar oferta" } as const)[kind]; }
