"use client";
import { useEffect, useState } from "react";
import type { AffiliateOffer, AutonomyJob, AutonomyPolicy, AutonomyStatus, ContentAsset, DistributionCampaign, MarketOpportunity } from "@atlas/types";
const api = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:3333";

export default function OffersPage() {
  const [token, setToken] = useState(""); const [offers, setOffers] = useState<AffiliateOffer[]>([]); const [opportunities, setOpportunities] = useState<MarketOpportunity[]>([]); const [campaigns, setCampaigns] = useState<DistributionCampaign[]>([]); const [jobs, setJobs] = useState<AutonomyJob[]>([]); const [assets, setAssets] = useState<ContentAsset[]>([]); const [status, setStatus] = useState<AutonomyStatus | null>(null); const [policy, setPolicy] = useState<AutonomyPolicy | null>(null); const [error, setError] = useState(""); const [busyId, setBusyId] = useState("");
  useEffect(() => { const saved = localStorage.getItem("atlas_token") ?? ""; setToken(saved); if (saved) void refresh(saved); }, []);
  const auth = (active = token) => ({ authorization: `Bearer ${active}` });
  async function refresh(active = token) { try { const paths = ["market/offers", "market/opportunities", "distribution/campaigns", "autonomy/jobs", "content/assets", "autonomy/status", "autonomy/policy"]; const responses = await Promise.all(paths.map((path) => fetch(`${api}/${path}`, { headers: auth(active) }))); if (responses.some((item) => !item.ok)) throw new Error("Não foi possível carregar a operação"); const [o,p,c,j,x,s,a] = await Promise.all(responses.map((item) => item.json())); setOffers(o); setOpportunities(p); setCampaigns(c); setJobs(j); setAssets(x); setStatus(s); setPolicy(a); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Falha ao carregar a Central de Ofertas"); } }
  async function toggle() { if (!policy) return; const response = await fetch(`${api}/autonomy/policy`, { method: "PATCH", headers: { ...auth(), "content-type": "application/json" }, body: JSON.stringify({ enabled: !policy.enabled }) }); if (!response.ok) { setError((await response.json()).message); return; } setPolicy(await response.json()); }
  async function review(id: string, decision: "approved" | "rejected") { setBusyId(id); setError(""); try { const response = await fetch(`${api}/content/assets/${id}/review`, { method: "PATCH", headers: { ...auth(), "content-type": "application/json" }, body: JSON.stringify({ status: decision, notes: decision === "approved" ? "Aprovado pela Central de Ofertas" : "Devolvido para revisão pela Central de Ofertas" }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.message ?? "Não foi possível registrar sua decisão"); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Falha na aprovação"); } finally { setBusyId(""); } }
  const qualified = opportunities.filter((item) => item.status === "qualified").length; const delivered = campaigns.filter((item) => item.result?.delivered).length; const reviewQueue = assets.filter((item) => item.status === "in_review");
  return <main className="mission-shell"><aside className="sidebar"><a className="brand" href="/"><span className="brand-mark">A</span>Atlas<span className="muted"> 2.0</span></a><nav><a className="nav-link" href="/">Oportunidades</a><a className="nav-link active">Central de Ofertas</a><a className="nav-link" href="/distribution">Distribuição</a><a className="nav-link" href="/operation">Operação</a></nav></aside><section className="content offers-content"><header className="topbar"><div><span className="eyebrow">RADAR DE ESCOLHAS · OPERAÇÃO MULTICANAL</span><h1>Central de Ofertas</h1></div><button className="new-button" onClick={() => void refresh()}>Atualizar</button></header>{error && <p className="error-banner">{error}</p>}
  <section className="offers-hero"><div><span className={`autonomy-light ${policy?.enabled && status?.enabled ? "on" : ""}`}/><strong>{policy?.enabled && status?.enabled ? "Operação autônoma ativa" : "Ativação protegida"}</strong><p>O Atlas só entra em operação integral após o worker e os conectores oficiais passarem pela validação de produção.</p></div><button className="safety-button" onClick={() => void toggle()}>{policy?.enabled ? "Pausar empresa" : "Autorizar pela política"}</button></section>
  <section className="offer-metrics"><Metric value={offers.length} label="ofertas encontradas"/><Metric value={qualified} label="oportunidades qualificadas"/><Metric value={reviewQueue.length} label="conteúdos para aprovar"/><Metric value={delivered} label="publicações confirmadas"/></section>
  <section className="approval-panel"><div className="approval-heading"><div><span className="eyebrow">SUA APROVAÇÃO · CELULAR</span><h2>Conteúdos aguardando decisão</h2><p>Leia o texto completo. Aprovar libera a peça para a próxima etapa; não publica automaticamente.</p></div><a href="/content">Abrir estúdio</a></div>{!reviewQueue.length && <p className="empty-state">Nenhum conteúdo aguardando sua aprovação.</p>}<div className="approval-list">{reviewQueue.map((asset) => <article className="approval-card" key={asset.id}><div className="approval-meta"><span>{channelLabel(asset.channel)}</span><small>{asset.format}</small></div><h3>{asset.title}</h3><p>{asset.body}</p>{asset.cta && <div className="approval-cta"><strong>Chamada:</strong> {asset.cta}</div>}<div className="approval-actions"><button className="new-button" disabled={busyId === asset.id} onClick={() => void review(asset.id, "approved")}>Aprovar conteúdo</button><button disabled={busyId === asset.id} onClick={() => void review(asset.id, "rejected")}>Pedir revisão</button></div></article>)}</div></section>
  <section className="offers-grid"><article className="panel"><span className="eyebrow">FILA AUTÔNOMA</span><h2>Próximas ações</h2>{jobs.slice(0,8).map((job) => <div className="offer-row" key={job.id}><div><strong>{labelJob(job.kind)}</strong><small>{job.idempotencyKey}</small></div><span className={`job-status ${job.status}`}>{job.status}</span></div>)}{!jobs.length && <p className="empty-state">Nenhuma tarefa na fila.</p>}</article><article className="panel"><span className="eyebrow">CURADORIA</span><h2>Produtos em análise</h2>{offers.slice(0,8).map((offer) => <div className="offer-row" key={offer.id}><div><strong>{offer.name}</strong><small>{offer.provider} · {offer.notes || "aguardando validação"}</small></div>{offer.commission !== undefined && <b>{offer.commission}%</b>}</div>)}{!offers.length && <p className="empty-state">A descoberta automática ainda não foi ativada.</p>}</article></section>
  <section className="panel policy-panel"><span className="eyebrow">GUARDIÃO OPERACIONAL</span><h2>Limites atuais</h2><div className="policy-grid"><span><b>{policy?.maxPostsPerChannelPerDay ?? "—"}</b> publicações por canal/dia</span><span><b>{policy?.duplicateCooldownHours ?? "—"}h</b> sem repetir oferta</span><span><b>{policy?.quietHoursStart ?? "—"}–{policy?.quietHoursEnd ?? "—"}</b> horário silencioso</span><span><b>{policy?.requireLicensedMedia ? "Obrigatória" : "Desativada"}</b> licença de mídia</span></div></section>
  </section></main>;
}
function Metric({ value, label }: { value: number; label: string }) { return <article><strong>{value}</strong><span>{label}</span></article>; }
function labelJob(kind: AutonomyJob["kind"]) { return ({ discover_offers: "Descobrir ofertas", validate_offer: "Validar produto", prepare_content: "Preparar conteúdo", publish_content: "Publicar conteúdo", refresh_metrics: "Atualizar resultados", expire_offer: "Encerrar oferta" } as const)[kind]; }
function channelLabel(channel: ContentAsset["channel"]) { return ({ instagram: "Instagram", tiktok: "TikTok", youtube: "YouTube", pinterest: "Pinterest", telegram: "Telegram", whatsapp: "WhatsApp", blog: "Blog", email: "E-mail", "landing-page": "Página" } as const)[channel] ?? channel; }
