import { createHmac, randomBytes, scryptSync, timingSafeEqual } from "node:crypto";
import type { AtlasUser, AuthSession } from "@atlas/types";
import type { CollectionStore } from "@atlas/core";

export type StoredUser = AtlasUser & { passwordHash: string; salt: string };
export class AuthService {
  constructor(private readonly users: CollectionStore<StoredUser>, private readonly secret = process.env.AUTH_SECRET ?? randomBytes(32).toString("hex"), private readonly ttlSeconds = 86400) {}
  async register(email: string, password: string, name: string): Promise<AuthSession> { const normalized = email.trim().toLowerCase(); if (!/^\S+@\S+\.\S+$/.test(normalized)) throw new Error("Invalid email"); if (password.length < 8) throw new Error("Password must have at least 8 characters"); const users = await this.users.load(); if (users.some((user) => user.email === normalized)) throw new Error("Email already registered"); const salt = randomBytes(16).toString("hex"); const user: StoredUser = { id: crypto.randomUUID(), email: normalized, name: name.trim(), role: users.length ? "member" : "admin", createdAt: new Date().toISOString(), salt, passwordHash: scryptSync(password, salt, 32).toString("hex") }; users.push(user); await this.users.save(users); return this.session(user); }
  async login(email: string, password: string): Promise<AuthSession> { const user = (await this.users.load()).find((item) => item.email === email.trim().toLowerCase()); if (!user) throw new Error("Invalid credentials"); const actual = scryptSync(password, user.salt, 32); const expected = Buffer.from(user.passwordHash, "hex"); if (actual.length !== expected.length || !timingSafeEqual(actual, expected)) throw new Error("Invalid credentials"); return this.session(user); }
  verify(token: string): AtlasUser { const [payload, signature] = token.split("."); if (!payload || !signature) throw new Error("Invalid token"); const expected = this.sign(payload); if (signature.length !== expected.length || !timingSafeEqual(Buffer.from(signature), Buffer.from(expected))) throw new Error("Invalid token"); const data = JSON.parse(Buffer.from(payload, "base64url").toString()) as AtlasUser & { exp: number }; if (data.exp < Math.floor(Date.now() / 1000)) throw new Error("Token expired"); const { exp: _exp, ...user } = data; return user; }
  private session(user: StoredUser): AuthSession { const expires = Math.floor(Date.now() / 1000) + this.ttlSeconds; const safe: AtlasUser = { id: user.id, email: user.email, name: user.name, role: user.role, createdAt: user.createdAt }; const payload = Buffer.from(JSON.stringify({ ...safe, exp: expires })).toString("base64url"); return { token: `${payload}.${this.sign(payload)}`, user: safe, expiresAt: new Date(expires * 1000).toISOString() }; }
  async firstAdmin(): Promise<AtlasUser | undefined> { const user = (await this.users.load()).find((item) => item.role === "admin"); return user ? { id: user.id, email: user.email, name: user.name, role: user.role, createdAt: user.createdAt } : undefined; }
  private sign(payload: string): string { return createHmac("sha256", this.secret).update(payload).digest("base64url"); }
  close(): void { this.users.close?.(); }
}
