"use client";
import { type FormEvent, useEffect, useState } from "react";
import type { ContentAsset, ContentChannel, DistributionCampaign } from "@atlas/types";
import "../mission.css";
import "./distribution.css";
const api = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:3333";

export default function DistributionPage() {
  const [token, setToken] = useState(""), [assets, setAssets] = useState<ContentAsset[]>([]), [campaigns, setCampaigns] = useState<DistributionCampaign[]>([]), [assetId, setAssetId] = useState(""), [destination, setDestination] = useState("Canal principal"), [targetUrl, setTargetUrl] = useState("https://example.com/oferta"), [campaignName, setCampaignName] = useState("Campanha Atlas"), [scheduledAt, setScheduledAt] = useState("2026-08-09T12:00"), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const headers = (json = false) => ({ authorization: `Bearer ${token}`, ...(json ? { "content-type": "application/json" } : {}) });
  async function refresh(activeToken = token) { const auth = { authorization: `Bearer ${activeToken}` }; const [assetResponse, campaignResponse] = await Promise.all([fetch(`${api}/content/assets`, { headers: auth }), fetch(`${api}/distribution/campaigns`, { headers: auth })]); if (!assetResponse.ok || !campaignResponse.ok) throw new Error("Sessão expirada ou API indisponível"); const nextAssets = (await assetResponse.json() as ContentAsset[]).filter((item) => item.status === "approved"); setAssets(nextAssets); setCampaigns(await campaignResponse.json()); setAssetId((value) => value || nextAssets[0]?.id || ""); }
  useEffect(() => { const saved = localStorage.getItem("atlas_token") ?? ""; setToken(saved); if (saved) void refresh(saved).catch((reason) => setError(reason.message)); }, []);
  async function create(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const asset = assets.find((item) => item.id === assetId); if (!asset) throw new Error("Selecione um conteúdo aprovado"); const response = await fetch(`${api}/distribution/campaigns`, { method: "POST", headers: headers(true), body: JSON.stringify({ assetId, channel: asset.channel, destination, scheduledAt: new Date(scheduledAt).toISOString(), targetUrl, campaignName, mode: "dry_run" }) }); if (!response.ok) throw new Error((await response.json()).message); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Falha ao criar campanha"); } finally { setBusy(false); } }
  async function advance(campaign: DistributionCampaign) { setBusy(true); setError(""); try { const action = campaign.status === "draft" ? "approve" : campaign.status === "approved" ? "schedule" : campaign.status === "scheduled" ? "execute" : ""; if (!action) return; const response = await fetch(`${api}/distribution/campaigns/${campaign.id}/${action}`, { method: "POST", headers: headers() }); if (!response.ok) throw new Error((await response.json()).message); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Falha ao avançar campanha"); } finally { setBusy(false); } }
  if (!token) return <main className="distribution-page"><section className="panel"><h1>Entre primeiro no Atlas</h1><a href="/">Voltar ao login</a></section></main>;
  return <main className="mission-shell"><aside className="sidebar"><a className="brand" href="/"><span className="brand-mark">A</span>atlas<span className="muted">.os</span></a><nav><a className="nav-link" href="/">Oportunidades</a><a className="nav-link" href="/content">Conteúdo</a><a className="nav-link active">Distribuição</a><a className="nav-link" href="/operation">Operação</a></nav></aside><section className="content mission-content"><header className="topbar"><div><span className="eyebrow">DISTRIBUTION CENTER · v0.7</span><h1>Conteúdo aprovado,<br/><em>distribuição controlada.</em></h1></div></header>{error && <p className="error-banner">{error}</p>}<section className="distribution-grid"><form className="panel mission-form" onSubmit={create}><span className="eyebrow">NOVA CAMPANHA</span><h2>Preparar distribuição</h2><label>Conteúdo aprovado<select value={assetId} onChange={(event) => setAssetId(event.target.value)} required><option value="">Selecione</option>{assets.map((item) => <option key={item.id} value={item.id}>{item.title} · {item.channel}</option>)}</select></label><label>Destino<input value={destination} onChange={(event) => setDestination(event.target.value)} required/></label><label>URL da oferta<input type="url" value={targetUrl} onChange={(event) => setTargetUrl(event.target.value)} required/></label><label>Nome da campanha<input value={campaignName} onChange={(event) => setCampaignName(event.target.value)} required/></label><label>Agendamento<input type="datetime-local" value={scheduledAt} onChange={(event) => setScheduledAt(event.target.value)} required/></label><small>Modo seguro: simulação. Nenhuma publicação externa ocorrerá.</small><button className="new-button" disabled={busy || !assetId}>Criar campanha</button></form><section className="panel"><span className="eyebrow">CONTROLE OPERACIONAL</span><h2>Campanhas</h2>{campaigns.length === 0 && <p className="empty-state">Nenhuma campanha preparada.</p>}{campaigns.map((campaign) => <article className="distribution-card" key={campaign.id}><span className={`mission-status ${campaign.status === "completed" ? "completed" : campaign.status === "failed" ? "failed" : ""}`}>{campaign.status}</span><h3>{campaign.utm.campaign}</h3><p>{campaign.channel} · {campaign.destination}</p><a href={campaign.trackingUrl} target="_blank" rel="noreferrer">Link rastreável</a><small>{new Date(campaign.scheduledAt).toLocaleString("pt-BR")} · {campaign.mode}</small>{campaign.result && <p>{campaign.result.detail}</p>}{["draft", "approved", "scheduled"].includes(campaign.status) && <button className="new-button" disabled={busy} onClick={() => void advance(campaign)}>{campaign.status === "draft" ? "Aprovar" : campaign.status === "approved" ? "Agendar" : "Executar simulação"}</button>}</article>)}</section></section></section></main>;
}
