"use client";
import { useEffect, useState } from "react";
import type { CompanyCycle } from "@atlas/types";
import "../mission.css";
import "./company.css";
const api = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:3333";

export default function CompanyPage() {
  const [token, setToken] = useState(""), [cycles, setCycles] = useState<CompanyCycle[]>([]), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  async function refresh(activeToken = token) { const response = await fetch(`${api}/company/cycles`, { headers: { authorization: `Bearer ${activeToken}` } }); if (!response.ok) throw new Error("Sessão expirada ou API indisponível"); setCycles(await response.json()); }
  useEffect(() => { const saved = localStorage.getItem("atlas_token") ?? ""; setToken(saved); if (saved) void refresh(saved).catch((reason) => setError(reason.message)); }, []);
  async function assess() { setBusy(true); setError(""); try { const response = await fetch(`${api}/company/cycles/assess`, { method: "POST", headers: { authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error((await response.json()).message); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Falha ao avaliar empresa"); } finally { setBusy(false); } }
  if (!token) return <main className="company-page"><section className="panel"><h1>Entre primeiro no Radar de Escolhas</h1><a href="/">Voltar ao login</a></section></main>;
  const cycle = cycles[0];
  return <main className="mission-shell"><aside className="sidebar"><a className="brand" href="/"><span className="brand-mark">R</span>Radar<span className="muted"> de Escolhas</span></a><nav><a className="nav-link" href="/">Oportunidades</a><a className="nav-link" href="/content">Conteúdo</a><a className="nav-link" href="/distribution">Distribuição</a><a className="nav-link" href="/learning">Aprendizado</a><a className="nav-link" href="/scale">Escala</a><a className="nav-link active">Empresa</a></nav></aside><section className="content mission-content"><header className="topbar"><div><span className="eyebrow">RADAR DE ESCOLHAS · v1.0</span><h1>Uma empresa guiada<br/><em>por evidências.</em></h1></div><button className="new-button" disabled={busy} onClick={() => void assess()}>Avaliar ciclo</button></header>{error && <p className="error-banner">{error}</p>}{!cycle && <section className="panel empty-state">Execute a primeira avaliação do ciclo empresarial.</section>}{cycle && <><section className="company-hero"><span className={`company-state ${cycle.status}`}>{cycle.status}</span><h2>Próxima ação</h2><p>{cycle.nextAction}</p><small>Modo {cycle.mode} · publicação externa desativada · execução financeira desativada</small></section><section className="company-stages">{cycle.stages.map((stage, index) => <article className="panel" key={stage.name}><b>{index + 1}</b><span className={`mission-status ${stage.status === "completed" ? "completed" : "failed"}`}>{stage.status}</span><h3>{stage.name}</h3><strong>{stage.count}</strong><p>{stage.detail}</p></article>)}</section>{cycle.blockers.length > 0 && <section className="panel blockers"><h2>Exceções que exigem atenção</h2>{cycle.blockers.map((item) => <p key={item}>{item}</p>)}</section>}</>}</section></main>;
}
