"use client";
import { useEffect, useState } from "react";
import type { AgentExecution, AtlasAgent, AtlasStatus, Decision, KnowledgeItem, MemoryItem, OperationLog, PluginManifest } from "@atlas/types";
const api = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:3333";
type Operation = { status: AtlasStatus; counts: Record<string, number>; uptimeSeconds: number; lastExecutionAt: string | null };
type Performance = { executions: number; averageElapsedMs: number; failures: number; cancellations: number };

export default function OperationPage() {
  const [token, setToken] = useState("");
  const [operation, setOperation] = useState<Operation | null>(null); const [logs, setLogs] = useState<OperationLog[]>([]); const [knowledge, setKnowledge] = useState<KnowledgeItem[]>([]); const [memory, setMemory] = useState<MemoryItem[]>([]); const [decisions, setDecisions] = useState<Decision[]>([]); const [agents, setAgents] = useState<AtlasAgent[]>([]); const [executions, setExecutions] = useState<AgentExecution[]>([]); const [plugins, setPlugins] = useState<PluginManifest[]>([]); const [performance, setPerformance] = useState<Performance | null>(null); const [config, setConfig] = useState<{ provider:string;model:string;temperature:number;mockEnabled:boolean } | null>(null); const [error, setError] = useState("");
  useEffect(() => { const saved = localStorage.getItem("atlas_token") ?? ""; setToken(saved); if (saved) void refresh(saved); }, []);
  async function refresh(activeToken = token) { try { const paths = ["operation", "logs", "knowledge", "memory", "decisions", "agents", "agent-executions", "plugins", "performance", "config"]; const responses = await Promise.all(paths.map((path) => fetch(`${api}/atlas/${path}`, { headers: { authorization: `Bearer ${activeToken}` } }))); if (responses.some((response) => !response.ok)) throw new Error(); const [o,l,k,m,d,a,x,p,f,c] = await Promise.all(responses.map((response) => response.json())); setOperation(o); setLogs(l); setKnowledge(k); setMemory(m); setDecisions(d); setAgents(a); setExecutions(x); setPlugins(p); setPerformance(f); setConfig(c); setError(""); } catch { setError("A API do Atlas não está acessível ou a sessão expirou."); } }
  return <main className="mission-shell"><aside className="sidebar"><a className="brand" href="/"><span className="brand-mark">A</span>atlas<span className="muted">.os</span></a><nav><a className="nav-link" href="/">Mission Control</a><a className="nav-link active">Operação</a></nav></aside><section className="content mission-content"><header className="topbar"><div><span className="eyebrow">AUTONOMOUS INTELLIGENCE</span><h1>Agentes, contexto<br/><em>e execução real.</em></h1></div><button className="new-button" onClick={() => void refresh()}>Atualizar</button></header>{error && <p className="error-banner">{error}</p>}
  {operation && <section className="operation-grid"><Panel label="DASHBOARD" title={`Atlas ${operation.status.version}`}><p>Core: <strong>{operation.status.lifecycle}</strong> · IA: <strong>{operation.status.ai.provider} / {operation.status.ai.model}</strong></p><p>Uptime: {operation.uptimeSeconds}s · última execução: {operation.lastExecutionAt ?? "—"}</p><div className="counts">{Object.entries(operation.counts).map(([name,value]) => <span key={name}><b>{value}</b>{name}</span>)}</div></Panel><Panel label="MÓDULOS" title="Status">{operation.status.modules.map((module) => <div className="module-row" key={module.name}><span className="state-dot online"/>{module.name}<small>{module.status}</small></div>)}</Panel></section>}
  <section className="operation-grid"><Panel label="AGENTES" title="Atlas Executive Agent">{agents.map((agent) => <p key={agent.id}><strong>{agent.name}</strong> · {agent.status} · missão {agent.currentMissionId ?? "—"} · memória {agent.memoryUsed ?? 0} · provider {agent.provider ?? "—"}</p>)}{executions.slice(0,5).map((item) => <p key={item.id}>{item.state} · {item.elapsedMs}ms · missão {item.missionId.slice(0,8)}</p>)}</Panel><Panel label="PERFORMANCE" title="Execuções"><p>Total: <strong>{performance?.executions ?? 0}</strong> · média {performance?.averageElapsedMs ?? 0}ms</p><p>Falhas: {performance?.failures ?? 0} · cancelamentos: {performance?.cancellations ?? 0}</p></Panel></section>
  <section className="operation-grid"><Panel label="MEMÓRIA" title="Contexto reutilizável">{memory.slice(0,5).map((item) => <p key={item.id}><strong>{Math.round((item.priority ?? 0)*100)}%</strong> · {item.summary} · referências {item.relatedMemoryIds?.length ?? 0}</p>)}{!memory.length && <p className="empty-state">Nenhuma memória registrada.</p>}</Panel><Panel label="KNOWLEDGE V3" title="Conhecimento">{knowledge.slice(0,5).map((item) => <p key={item.id}><strong>{item.namespace ?? "default"}</strong> · {item.summary}</p>)}{!knowledge.length && <p className="empty-state">Nenhum conhecimento registrado.</p>}</Panel></section>
  <section className="operation-grid"><Panel label="PLUGINS" title="Runtime">{plugins.map((plugin) => <p key={plugin.id}><strong>{plugin.name} {plugin.version}</strong> · {plugin.status} · {plugin.capabilities.join(", ")}</p>)}</Panel><Panel label="DECISION V3" title="Decisões">{decisions.slice(0,5).map((decision) => <p key={decision.id}><strong>{Math.round((decision.adjustedConfidence ?? decision.confidence)*100)}%</strong> · {decision.recommendation} · {decision.alternatives?.length ?? 0} alternativas</p>)}</Panel></section>
  <section className="operation-grid"><Panel label="EVENTOS" title="Auditoria recente">{logs.slice(0,10).map((log) => <p key={log.id}><strong className={`log-${log.severity}`}>{log.severity}</strong> · {log.module} / {log.action}</p>)}</Panel><Panel label="PROVIDER" title="Configuração segura"><p><strong>{config?.provider}</strong> · {config?.model}</p><p>Mock automático: {config?.mockEnabled ? "ativo" : "inativo"}</p></Panel></section>
  </section></main>;
}
function Panel({ label, title, children }: { label: string; title: string; children: React.ReactNode }) { return <article className="panel"><span className="eyebrow">{label}</span><h2>{title}</h2>{children}</article>; }
